Repository zhihu/griffith, pull requests merged in 2019-03, with the labels that each got.

#19 fix fullscreen related issues
  packages/griffith/package.json
  packages/griffith/src/components/Player/Player.js
  packages/griffith/src/components/PlayerContainer/PlayerContainer.js
  packages/griffith/src/contexts/VideoSource/VideoSourceProvider.js
  yarn.lock
Labels: bug🐛, enhancement✨

#26 fix: some MSE error
  packages/griffith-mp4/src/mse/controller.js
  packages/griffith-mp4/src/player.js
Labels: bug🐛

#34 docs: japanese version
  README-ja_JP.md
  README-zh_CN.md
  README.md
Labels: enhancement✨

#43 feat: add buffered cache
  .eslintignore
  .prettierignore
  package.json
  packages/griffith-mp4/src/mse/controller.js
Labels: enhancement✨

#48 fix: Cannot read property appendBuffer of undefined
  packages/griffith-mp4/src/mse/controller.js
Labels: bug🐛

#49 feat: multiple sourcebuffer
  packages/griffith-mp4/src/fmp4/__tests__/fmp4Generator.spec.js
  packages/griffith-mp4/src/fmp4/boxes/__tests__/moov.spec.js
  packages/griffith-mp4/src/fmp4/boxes/moov.js
  packages/griffith-mp4/src/fmp4/fmp4Generator.js
  packages/griffith-mp4/src/mp4/boxes/elst.js
  packages/griffith-mp4/src/mp4/utils/__tests__/findBox.spec.js
  packages/griffith-mp4/src/mp4/utils/__tests__/getSamplesInterval.spec.js
  packages/griffith-mp4/src/mp4/utils/findBox.js
  packages/griffith-mp4/src/mp4/utils/getSamplesInterval.js
  packages/griffith-mp4/src/mse/controller.js
Labels: enhancement✨
